import * as fs from 'fs';
import * as path from 'path';
import * as agentsconf from './agentsconf';
import * as fsutil from './fsutil';
import * as adapters from './adapters';

/**
 * Resolve the canonical templates directory shipped with the package.
 * In dev (ts-node) and prod (dist) __dirname differs, so try a few roots.
 */
export function getTemplatesDir(): string {
  const candidates = [
    path.join(__dirname, '..', '..', 'templates', 'canonical'),
    path.join(__dirname, '..', '..', 'src', 'templates', 'canonical'),
    path.join(process.cwd(), 'templates', 'canonical'),
  ];
  for (const dir of candidates) {
    if (fs.existsSync(path.join(dir, 'agents'))) return dir;
  }
  throw new Error('Templates directory not found. Ensure templates/canonical/ exists.');
}

/**
 * Render the canonical source through a tool adapter and write every artifact
 * to its native path. No symlinks. Shared by `init` and `update`.
 */
export function renderProject(
  tool: string,
  projectDir: string,
  mode: string,
  config: agentsconf.Config
): void {
  const adapter = adapters.registry.get(tool);
  if (!adapter) {
    const known = adapters.registry.getAll().map((a) => a.toolId).join(', ') || '(none)';
    throw new Error(`Tool '${tool}' has no adapter. Registered: ${known}.`);
  }

  const scope: adapters.Scope = mode === 'global' ? 'global' : 'project';
  const ctx: adapters.RenderContext = {
    config,
    projectDir,
    projectName: path.basename(projectDir),
    stack: adapters.detectStack(projectDir),
  };

  const artifacts = adapters.loadCanonical(getTemplatesDir());
  // Synthetic tool-config artifact (e.g. opencode.json) — generated by the adapter.
  artifacts.push({ kind: 'config', id: 'tool-config', meta: {}, body: '' });

  for (const artifact of artifacts) {
    const content = adapter.render(artifact, ctx);
    if (content == null) continue; // adapter does not emit this kind
    const dest = adapter.getFilePath(artifact, scope, projectDir);
    fsutil.ensureDir(path.dirname(dest));
    fs.writeFileSync(dest, content, 'utf-8');
  }
}
